Internet Programming/MVC__Fluffy_Duffy_Munchkin_Cats/MVC__Fluffy_Duffy_Munchkin_Cats/Models/Cat.cs
using System.ComponentModel.DataAnnotations;

namespace MVC__Fluffy_Duffy_Munchkin_Cats.Models
{
    public class Cat
    {
        [Key]
        public int ID { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Breed { get; set; }
        public string Img_Url { get; set; }
    }
}

Internet Programming/MVC__Fluffy_Duffy_Munchkin_Cats/MVC__Fluffy_Duffy_Munchkin_Cats/Models/ErrorViewModel.cs
namespace MVC__Fluffy_Duffy_Munchkin_Cats.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Internet Programming/MVC__Fluffy_Duffy_Munchkin_Cats/MVC__Fluffy_Duffy_Munchkin_Cats/Controllers/CatController.cs
using Microsoft.AspNetCore.Mvc;
using MVC__Fluffy_Duffy_Munchkin_Cats.Data;
using MVC__Fluffy_Duffy_Munchkin_Cats.Models;

namespace MVC__Fluffy_Duffy_Munchkin_Cats.Controllers
{
    public class CatController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CatController(ApplicationDbContext context)
        {
            this._context = context;
        }
        public IActionResult Index()
        {
            var cats = _context.Cats.ToList();
            return View(cats);
        }
        public IActionResult Search(string searchName)
        {
            var allCats = _context.Cats.ToList();

            var searchResult = allCats.Where(cat => cat.Name.Contains(searchName)).ToList();

            return View(searchResult);
        }

        public IActionResult Add()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            var cat = _context.Cats.Where(x => x.ID == id).SingleOrDefault();
            if (cat == null)
            {
                return NotFound();
            }
            return View(cat);
        }

        [HttpPost]
        public IActionResult Add(Cat cat)
        {
            _context.Cats.Add(cat);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Update(int id)
        {
            var data = _context.Cats.Where
                (x => x.ID == id).SingleOrDefault();
            return View(data);
        }

        [HttpPost]
        public ActionResult Update(int id, Cat cat)
        {
            var catData = _context.Cats.
                FirstOrDefault(x => x.ID == id);

            if (catData != null)
            {
                catData.Name = cat.Name;
                catData.Age = cat.Age;
                catData.Breed = cat.Breed;
                catData.Img_Url = cat.Img_Url;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }
        public IActionResult Delete(int id)
        {
            var cat = _context.Cats.FirstOrDefault(x => x.ID == id);
            if (cat == null)
            {
                return NotFound();
            }
            return View(cat);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var cat = _context.Cats.FirstOrDefault(x => x.ID == id);
            if (cat == null)
            {
                return NotFound();
            }
            _context.Cats.Remove(cat);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Internet Programming/MVC__Fluffy_Duffy_Munchkin_Cats/MVC__Fluffy_Duffy_Munchkin_Cats/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC__Fluffy_Duffy_Munchkin_Cats.Models;
using System.Diagnostics;

namespace MVC__Fluffy_Duffy_Munchkin_Cats.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Internet Programming/MVC__Fluffy_Duffy_Munchkin_Cats/MVC__Fluffy_Duffy_Munchkin_Cats/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Mrrr!Meow! </h1>
    <a asp-controller="Cat" asp-action="Add" class="btn btn-primary">Add</a>
    <br>
    <a asp-controller="Cat" asp-action="Index" class="btn btn-primary" >Cat List </a>
</div>

Internet Programming/MVC__Fluffy_Duffy_Munchkin_Cats/MVC__Fluffy_Duffy_Munchkin_Cats/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC__Fluffy_Duffy_Munchkin_Cats</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC__Fluffy_Duffy_Munchkin_Cats.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC__Fluffy_Duffy_Munchkin_Cats</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVC__Fluffy_Duffy_Munchkin_Cats - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>